services:
  api_gateway:
    container_name: api_gateway
    image: kong
    volumes:
      - ./gateway:/app
    environment:
      - KONG_DATABASE=off
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_DECLARATIVE_CONFIG=/app/kong.yml
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    command: kong start

  customer_service:
    container_name: customer
    build: ./customer
    volumes:
      - ./customer:/app
    ports:
      - 81:81

  product_service:
    container_name: product
    build: ./product
    volumes:
      - ./product:/app
    ports:
      - 82:82
    environment:
      - platform=linux/amd64

  basket_service:
    container_name: basket
    build: ./basket
    volumes:
      - ./basket:/app
    ports:
      - 83:83
